Import('env')

includes = [
    '#core/include',
    '#core/include/cmsis',
    '#core/include/mcu'
]

if env['type'] == 'unittest':
    for h in ['include/nrf_error.h', 'include/nrf_assert.h', 'include/nrf_fault.h']:
        env.addCMock(h)

env.Append(CPPPATH=includes)
mcu     = SConscript('mcu/SConscript',      exports=['env'])
error   = SConscript('error/SConscript',    exports=['env'])

if env['type'] == 'build':
    env.addLibrary(
        target = 'core',
        source = mcu + error
    )
