Import('env')

includes = [
    '#core/include',
    '#core/include/cmsis',
    '#core/include/mcu'
]
env.Append(CPPPATH=includes)

env.addCMock(Glob('include/*.h'))

sources = list()
for module in ['mcu', 'error']:
    sources.append(SConscript(module + '/SConscript', exports=['env']))

env.addSource(
        target = 'core',
        source = sources
    )

env.addLibrary(
    target = 'core',
    source = sources
)
