Import('env')

import os, sys
work_dir = Dir('#.').path+'/'+os.path.dirname(File('SConscript').srcnode().path)

my_dirs = [d for d in os.listdir(work_dir) if os.path.isdir(os.path.join(work_dir, d))]

includes = [
    '#boards'
]
env.Append(CPPPATH=includes)

for board in my_dirs:
    lib = SConscript(board+'/SConscript',      exports=['env'])
    if env['type'] == 'build':
        env['lib']['boards'] = list()
        env['lib']['boards'].append(env.Library(
            target = board,
            source = lib
        )) 
