Import('env')

sources = list()
objects = list()

if env['MCU'].startswith('NRF51'):
    sources.append(File('system_nrf51.c'))

elif env['MCU'].startswith('NRF52'):
    sources.append(File('system_nrf52.c'))

if 'Object' in env['BUILDERS']:
    for s in sources:
        objects.append(env.Object(s))

result = {
    'sources' : sources,
    'objects' : objects
}
Return('result')