Import('env')

sources = [
    'nrf_assert.c',
    'nrf_error.c',
    'nrf_fault.c',
]

if env['type'] == 'build':
    objects = list()
    for s in sources:
        objects.append(env.Object(s))
    Return('objects')

elif env['type'] == 'unittest':
    SConscript('test/SConscript',    exports=['env'])