Import('env')

sources = [
    'nrf_assert.c',
    'nrf_error.c',
    'nrf_fault.c',
]

objects = list()
if 'Object' in env['BUILDERS']:
    for s in sources:
        objects.append(env.Object(s))

result = {
    'objects' : objects,
}
Return('result')