Import('env')

sources = [
    File('nrf_assert.c'),
    File('nrf_error.c'),
    File('nrf_fault.c'),
]

objects = list()
if 'Object' in env['BUILDERS']:
    for s in sources:
        objects.append(env.Object(s))

result = {
    'objects' : objects,
}
Return('result')