Import('env')

sources = [
    "main.c",
    '../../core/mcu/arm/arm_startup_nrf52.s'
]

# env['LINKFLAGS'] = ['-Tblinky_gcc_nrf51.ld']

# env.Hex(target = 'blinky', source = sources)
env.Keil5Project(target = 'blinky', src = sources);