import os
Import('env')

sources = [
    "main.c"
]

libs = [
    env['lib']['core']
]

ld_file = env.Linkgen(target = 'blinky')
env.addHex(target = 'blinky', source = sources, linker_file = ld_file, lib=libs)
env.Project(target = 'blinky', source = sources + libs)
